name: QA Control

on:
  push:
    branches:
      - develop
    paths:
      - src/**
      - tests/**
  pull_request:
    branches:
      - develop
    paths:
      - src/**
      - tests/**

jobs:
  main:
    name: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.2'
          tools: composer, pecl, phpunit
          extensions: curl, intl, json, mbstring, xdebug, xml, zip
          coverage: xdebug

      - name: Use latest Composer
        run: composer self-update

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --ansi --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix -v --config=.php_cs.dist --dry-run --stop-on-violation --using-cache=no
